baseurl = "https://xixitalk.github.io"
disablePathToLower = true
languageCode = "en-us"
title = "xixitalk's snippet"
theme = "hugo-octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
disqusShortname = "gitblog"

# Number of blog posts in each pagination page
paginate = 6
paginatePath = "blog/page"

pygmentsstyle = "solarized_dark"

# Use internal highlighter instead of Chroma
pygmentsUseClassic=true

# You need to install Solarized from https://github.com/john2x/solarized-pygment
# Octopress classic theme uses Solarized_dark
# Options are solarized_dark (octopress), solarized_dark256 and solarized_light

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# pygments options can be added here (and in the highlight shortcode in the markdown file)
# Hugo supports these pygments options: style, encoding, noclasses, hl_lines, linenos
# for example: pygmentsoptions = "linenos=true"

[permalinks]
post = "/blog/:year/:month/:day/:filename/" # change the post URL to look like the old ones

# Make tags and categories work
[indexes]
  tag = "tags"
  category = "categories"


[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 0

  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "About me"

  # Sidebar text also supports markdown
  # New lines can be added with </br> or normal markdown (two spaces at the end of line or two new lines).
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """[xixitalk@twitter](http://twitter.com/xixitalk)

[xixitalk@github](http://github.com/xixitalk)

My PGP <https://keybase.io/xixitalk/key.asc>

  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = false
  sidebarMenuHeader = "Sidebar Links"

  # sidebar links
  github = ""
  bitbucket = ""
  twitter = ""
  keybase = ""
  stackoverflow = ""
  linkedin = ""
  googleplus = ""
  youtube = ""
  facebook = ""
  instagram = ""

  # --- End sidebar options ---

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "xixitalk"

  # This text appears in the site header under website title
  subtitle = "Post Longer Than 140 Characters Tweets"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so it was added to index.html manually
  continueReadingText = "Read on"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-32324744-1"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  defaultDescription = ""

  # Populate this with your own search keywords - these will appear in the meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # CSS override files
  # Paths should be relative to the `static` directory
  # customCSS = ["css/custom.css","css/custom2.css"]

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here"

  notFoundText = """Please either go back or use the navigation/sidebar menus.
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # This is not needed unless alphabetical sort is needed
  # sortTaxonomyAlphabetical = true

# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window
[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -5

[[menu.main]]
  Name = "Tags"
  URL = "/tags/"
  weight = -5

# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
[[menu.sidebar]]
  Name = "Google"
  URL = "https://www.google.com"
  weight = 0

[[menu.sidebar]]
  Name = "Hugo"
  URL = "/categories/hugo/"
  weight = 1

[[menu.sidebar]]
  Name = "Homepage"
  URL = "/"
  weight = 2

# Blackfriday is Hugo's markdown engine. Options are at: https://gohugo.io/overview/configuration/#configure-blackfriday-rendering
[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false
